version: '3'
services:
  back:
    image: cake1234/wtw-backend
    container_name: 'wtw-backend'
    restart: always
    ports: 
      - ${BACK_PORT}:${BACK_PORT}
    environment: 
      - BACK_PORT=${BACK_PORT}
      - MONGO_PORT=${MONGO_PORT}
      - DOMAIN=${DOMAIN}
  
  front:
    image: cake1234/wtw-frontend
    container_name: 'wtw-frontend'
    restart: always
    ports:
      - ${FRONT_PORT}:${FRONT_PORT}
      
  database:
    image: mongo
    container_name: 'wtw-mongodb'
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
      