version: '3'
services:
  back:
    image: cake1234/wtw-backend
    container_name: 'wtw-backend'
    restart: always
    ports: 
      - 4001:4001
  
  front:
    image: cake1234/wtw-frontend
    container_name: 'wtw-frontend'
    restart: always
    ports:
      - 80:80
      
  database:
    image: mongo
    container_name: 'wtw-mongodb'
    restart: always
    ports:
      - 27017:27017
      