version: '3'
services:
  back:
    image: cake1234/wtw-backend
    container_name: 'wtw-backend'
    ports: 
      - "4001:4001"
  
  front:
    image: cake1234/wtw-frontend
    container_name: 'wtw-frontend'
    ports:
      - "80:80"
      
  database:
    image: mongo
    container_name: 'wtw-database'
    ports:
      - "27019:27019"
      